FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["EsqFeatureToggle/EsqFeatureToggle.csproj", "EsqFeatureToggle/"]
RUN dotnet restore "EsqFeatureToggle/EsqFeatureToggle.csproj"
COPY . .
WORKDIR "/src/EsqFeatureToggle"
RUN dotnet build "EsqFeatureToggle.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EsqFeatureToggle.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EsqFeatureToggle.dll"]